
import Classes.exciption;
import javax.swing.JOptionPane;
import Classes.*;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tawfek
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */int m=0,n=0;
    public Add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        insbool = new javax.swing.JRadioButton();
        mbool = new javax.swing.JRadioButton();
        user_name = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        hbool = new javax.swing.JRadioButton();
        id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        show = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add");
        setLocation(new java.awt.Point(500, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 102), new java.awt.Color(153, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insbool.setBackground(new java.awt.Color(255, 255, 255));
        insbool.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        insbool.setText("Inspector");
        insbool.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insboolMouseClicked(evt);
            }
        });
        insbool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insboolActionPerformed(evt);
            }
        });
        jPanel1.add(insbool, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 20));

        mbool.setBackground(new java.awt.Color(255, 255, 255));
        mbool.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        mbool.setText("Member");
        mbool.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mboolMouseClicked(evt);
            }
        });
        mbool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mboolActionPerformed(evt);
            }
        });
        jPanel1.add(mbool, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, 20));

        user_name.setBorder(null);
        user_name.setInheritsPopupMenu(true);
        user_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_nameMouseClicked(evt);
            }
        });
        jPanel1.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 210, 20));

        password.setBorder(null);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 210, 20));

        jButton1.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        jButton1.setText("Add");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 220, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 210, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 210, 10));

        hbool.setBackground(new java.awt.Color(255, 255, 255));
        hbool.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        hbool.setText("Head");
        hbool.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hboolMouseClicked(evt);
            }
        });
        hbool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hboolActionPerformed(evt);
            }
        });
        jPanel1.add(hbool, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 70, 20));

        id.setBorder(null);
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idMouseClicked(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 210, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, 10));

        jLabel3.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Jop");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 40));

        jLabel4.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel5.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, 20));

        jLabel6.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel6.setText("ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel7.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("User Information");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 40));

        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setFont(new java.awt.Font("Gabriola", 0, 17)); // NOI18N
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, 20));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 370, 460));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatar2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 230, 240));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shrook\\Desktop\\left.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Admin a=new Admin();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        password.setText((""));
    }//GEN-LAST:event_passwordMouseClicked

    private void user_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_nameMouseClicked
        String h= new String ();
        h=user_name.getText();
        if(h.equals("User Name"))
        {
            user_name.setText("");
        }
    }//GEN-LAST:event_user_nameMouseClicked

    private void mboolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mboolMouseClicked
     
          insbool.setSelected(false);
      
    }//GEN-LAST:event_mboolMouseClicked

    private void insboolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insboolMouseClicked

        mbool.setSelected(false);
        
    }//GEN-LAST:event_insboolMouseClicked

    private void mboolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mboolActionPerformed
        // TODO add your handling code here:
        hbool.setSelected(false);
        insbool.setSelected(false);
    }//GEN-LAST:event_mboolActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        if(hbool.isSelected()&&mbool.isSelected()&&insbool.isSelected()){
           exciption w=new exciption( "You have to one jop !");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption());
        }
        else if(hbool.isSelected()&&mbool.isSelected()||hbool.isSelected()&&insbool.isSelected()||mbool.isSelected()&&insbool.isSelected())
        {
                exciption w=new exciption( "You have to one jop !");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption());
        }
     else if(id.getText().equals("")||user_name.getText().equals("")||password.getText().equals("")) 
        {
             exciption w=new exciption( "You have to fill all Fields!");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption());
        }
     else {
         
        if(insbool.isSelected()){
            addmin a;
            try {
                a = new addmin();
                a.LoadUsers();
                if(a.Old.containsKey(id.getText())){
                         exciption w=new exciption( "this Id is already exist in the system !");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption());
                }
                else{  
                  a.add_user( id.getText(),user_name.getText(),password.getText(),"inspector");
               
            JOptionPane.showMessageDialog(rootPane, "Done");
                  id.setText("");
               user_name.setText("");
               password.setText("");
               hbool.setSelected(false);
               mbool.setSelected(false);
               insbool.setSelected(false);
                } 
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(mbool.isSelected()){
             addmin a;
            try {
                a = new addmin();
                    a.LoadUsers();
                if(a.Old.containsKey(id.getText())){
                         exciption w=new exciption( "this Id is already exist in the system !");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption());
                }
                else
                {
                            a.add_user( id.getText(),user_name.getText(),password.getText(),"member");
            id.setText("");
               user_name.setText("");
               password.setText("");
            JOptionPane.showMessageDialog(rootPane, "Done");
                }
           } catch (ClassNotFoundException ex) {
                Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(hbool.isSelected()){
                      addmin a;
            try {
                a = new addmin();
                  a.LoadUsers();
                if(a.Old.containsKey(id.getText())){
                         exciption w=new exciption( "this Id is already exist in the system !");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption());
                }
                else
                {
                            a.add_user( id.getText(),user_name.getText(),password.getText(),"head");
            id.setText("");
               user_name.setText("");
               password.setText("");
            JOptionPane.showMessageDialog(rootPane, "Done");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        else{
                exciption w=new exciption( "You have to choose The jop !");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption(),"Warning",JOptionPane.WARNING_MESSAGE);
        }
     
    }//GEN-LAST:event_jButton1ActionPerformed

        }catch(Exception e)
             {
             JOptionPane.showMessageDialog(rootPane,e,"Warning",JOptionPane.WARNING_MESSAGE);
             }
    }
    private void hboolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hboolMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hboolMouseClicked

    private void hboolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hboolActionPerformed
        // TODO add your handling code here:
        mbool.setSelected(false);
        insbool.setSelected(false);
    }//GEN-LAST:event_hboolActionPerformed

    private void idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseClicked
        if(id.getText().equals("ID"))
        {
            id.setText("");
        }
    }//GEN-LAST:event_idMouseClicked

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        if(show.isSelected()){
            password.setEchoChar((char)0);
        }
        else{
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_showActionPerformed

    private void insboolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insboolActionPerformed
        // TODO add your handling code here:
        mbool.setSelected(false);
        hbool.setSelected(false);
    }//GEN-LAST:event_insboolActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Admin a = new Admin();
        a.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked
int b=0;int o=0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton hbool;
    private javax.swing.JTextField id;
    private javax.swing.JRadioButton insbool;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton mbool;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox show;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
