/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tawfek
 */
import Classes.exciption;
import Classes.*;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
public class Addvol extends javax.swing.JFrame {

    /**
     * Creates new form Addvol
     */
    public Addvol() {
        initComponents();
    }
    String k;
  public Addvol(String s) {
        initComponents();
      k=s;
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        vadress = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vcomplain = new javax.swing.JTextArea();
        vname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        img = new javax.swing.JButton();
        vid = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        ins_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Voilation Details");
        setLocation(new java.awt.Point(500, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 204), new java.awt.Color(153, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 260, 10));

        vadress.setBorder(null);
        vadress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vadressMouseClicked(evt);
            }
        });
        vadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vadressActionPerformed(evt);
            }
        });
        jPanel1.add(vadress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 260, 20));
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 370, 200));

        vcomplain.setColumns(20);
        vcomplain.setRows(5);
        vcomplain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vcomplainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vcomplain);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 420, 110));

        vname.setBorder(null);
        vname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vnameMouseClicked(evt);
            }
        });
        vname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnameActionPerformed(evt);
            }
        });
        jPanel1.add(vname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 260, 10));

        jButton1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jButton1.setText("Add ");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 150, 30));

        img.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        img.setText("Browse Violaton Image");
        img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgActionPerformed(evt);
            }
        });
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 190, 30));

        vid.setBorder(null);
        vid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vidMouseClicked(evt);
            }
        });
        jPanel1.add(vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 260, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 260, 10));

        jLabel2.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("Voilation Information");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 250, 40));

        jLabel5.setFont(new java.awt.Font("Gabriola", 0, 22)); // NOI18N
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        jLabel6.setFont(new java.awt.Font("Gabriola", 0, 22)); // NOI18N
        jLabel6.setText("Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 50, 20));

        jLabel7.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel7.setText("Complaining");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 30));

        jLabel8.setFont(new java.awt.Font("Gabriola", 0, 22)); // NOI18N
        jLabel8.setText("Inspector Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 30));

        jButton2.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jButton2.setText("Add New");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 150, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 260, 10));

        jLabel9.setFont(new java.awt.Font("Gabriola", 0, 22)); // NOI18N
        jLabel9.setText("Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        ins_name.setBorder(null);
        jPanel1.add(ins_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 200, 260, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 480, 680));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shrook\\Desktop\\left.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipage-admin-icon.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 350, 390));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vadressActionPerformed
       
    }//GEN-LAST:event_vadressActionPerformed

    private void vcomplainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vcomplainMouseClicked
         String ss=new String();
        ss=vcomplain.getText();
        if(ss.equals("Complaining"))
        {
            vcomplain.setText("");
        }
    }//GEN-LAST:event_vcomplainMouseClicked

    private void vnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnameActionPerformed
       
    }//GEN-LAST:event_vnameActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       Inspector2 i=new Inspector2();
       i.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void vnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vnameMouseClicked
                String sss=new String();
        sss=vname.getText();
        if(sss.equals("Voilation Name"))
        {
            vname.setText("");
        }    }//GEN-LAST:event_vnameMouseClicked

    private void vadressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vadressMouseClicked
         String s=new String();
        s=vadress.getText();
        if(s.equals("Voilation Address"))
        {
            vadress.setText("");
        }
    }//GEN-LAST:event_vadressMouseClicked

    private void vidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vidMouseClicked
       if(vid.getText().equals("ID"))
       {
           vid.setText("");
       }
    }//GEN-LAST:event_vidMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(vid.getText().equals("")||vname.getText().equals("")||vcomplain.getText().equals("")||c==0||ins_name.getText().equals(""))
        { 
            exciption w=new exciption("please fill all rquired fields ");
                    JOptionPane.showMessageDialog(rootPane,w.view_exciption(),"Warning",JOptionPane.WARNING_MESSAGE);
        }
else {
     
        try {
            inspec b=new inspec ();
            b.LoadviolationAppointmentList();
            b.LoadviolationCurrentList();
                      if(b.timed_vio.containsKey(vid.getText())||b.Old_build.containsKey(vid.getText())){
                         exciption w=new exciption( "this Id is already exist in the system !");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption(),"Error",JOptionPane.ERROR_MESSAGE);
                }
                      else{
                      b.LoadUsers();boolean yes=false;
                                    for(Map.Entry k:b.Old.entrySet()){
               String key = k.getKey().toString();
               Vector vv=(Vector)k.getValue();
              if(vv.get(0).equals(ins_name.getText()))yes=true;
    
    }
                                    if(!yes){
                                           exciption w=new exciption("Inspector Name is Non exist ");
                    JOptionPane.showMessageDialog(rootPane,w.view_exciption(),"Error",JOptionPane.ERROR_MESSAGE);
                                    }                                             
                                              else {
       Violation a=new Violation(vid.getText(),vname.getText(),vadress.getText(),vcomplain.getText(),ins_name.getText(),image_path);
             b.add_violation(a);       
             vid.setEditable(false);
            vname.setEditable(false);
            vadress.setEditable(false);
            vcomplain.setEditable(false);
            img.setEnabled(false);
                         JOptionPane.showMessageDialog(this, "Done !!","Infomation",JOptionPane.INFORMATION_MESSAGE);
                      }
        
                                              }
        } catch (IOException ex) {
            Logger.getLogger(Addvol.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addvol.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     
}
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
 
        
    }//GEN-LAST:event_jButton1MouseClicked
    
    String image_path;
public ImageIcon ResizeImage(String ImagePath)
    {
        image_path=ImagePath;
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imag = new ImageIcon(newImg);
        return imag;
    }

    int c=0;
    private void imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgActionPerformed
        // TODO add your handling code here:
      c++;
        JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.home")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              String path = selectedFile.getAbsolutePath();
              image.setIcon(ResizeImage(path));
          image.setVisible(true);
          }
           //if the user click on save in Jfilechooser
          else if(result == JFileChooser.CANCEL_OPTION){
              JOptionPane.showMessageDialog(null," File Is Not Selected");
          }
    }//GEN-LAST:event_imgActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        vid.setEditable(true);
        vname.setEditable(true);
        vadress.setEditable(true);
        vcomplain.setEditable(true);
        vname.setText("");
        vadress.setText("");
        vcomplain.setText("");
        vid.setText("");
        img.setEnabled(true);
        image.setIcon(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addvol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JButton img;
    private javax.swing.JTextField ins_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField vadress;
    private javax.swing.JTextArea vcomplain;
    private javax.swing.JTextField vid;
    private javax.swing.JTextField vname;
    // End of variables declaration//GEN-END:variables
}
