import Classes.exciption;
import Classes.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tawfek
 */
public class Editvol extends javax.swing.JFrame {

    
    public Editvol() {
        initComponents();
        vio_name.setEditable(false);
        vio_add.setEditable(false);
        vio_com.setEditable(false);
        editButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vio_com = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        vio_add = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        vio_name = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        voi_id = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Complaining");
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 204), new java.awt.Color(153, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editButton.setFont(new java.awt.Font("Gabriola", 0, 22)); // NOI18N
        editButton.setText("Edit");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 220, 30));

        vio_com.setColumns(20);
        vio_com.setRows(5);
        jScrollPane1.setViewportView(vio_com);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 450, 170));

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel1.setText("Complaining");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        vio_add.setBorder(null);
        vio_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vio_addMouseClicked(evt);
            }
        });
        vio_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vio_addActionPerformed(evt);
            }
        });
        jPanel1.add(vio_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 250, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 250, 10));

        vio_name.setBorder(null);
        vio_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vio_nameMouseClicked(evt);
            }
        });
        vio_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vio_nameActionPerformed(evt);
            }
        });
        jPanel1.add(vio_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 250, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 250, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 240, 10));

        voi_id.setBorder(null);
        voi_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voi_idMouseClicked(evt);
            }
        });
        voi_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voi_idActionPerformed(evt);
            }
        });
        jPanel1.add(voi_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 240, 20));

        jButton2.setFont(new java.awt.Font("Gabriola", 0, 22)); // NOI18N
        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 140, 150, 30));

        jLabel4.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Voilation Information");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 250, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 520, 580));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shrook\\Desktop\\left.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipage-admin-icon.png"))); // NOI18N
        jPanel2.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 380, 380));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   protected ImageIcon createImageIcon(String path){
             java.net.URL imageUrl =getClass().getResource(path);
             if(imageUrl!=null){
                 return new ImageIcon(imageUrl);
             }
             else {
                 System.err.println("Couldn't find File : " + path);
                 return null;
             }
                      }
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       Inspector2 e=new  Inspector2();
       e.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void vio_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vio_nameActionPerformed
        
    }//GEN-LAST:event_vio_nameActionPerformed

    private void vio_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vio_nameMouseClicked
      String k=new String();
        k=vio_name.getText();
        if(k.equals("Enter Voilation Name"))
        {
            vio_name.setText("");
        }
    }//GEN-LAST:event_vio_nameMouseClicked

    private void vio_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vio_addActionPerformed
       
    }//GEN-LAST:event_vio_addActionPerformed

    private void vio_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vio_addMouseClicked
         String kk=new String();
       
        if(vio_add.getText().equals("Enter Voilation Address"))
        {
            vio_add.setText("");
        }
    }//GEN-LAST:event_vio_addMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if(voi_id.getText().equals("")){
                    exciption w=new exciption( "Please Enter the Id");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption());
        }
        else   if(voi_id.getText().equals("")||vio_name.getText().equals("")||vio_add.getText().equals("")||vio_com.getText().equals(""))
        {
              exciption w=new exciption(  "Please Enter all fields");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption());
        }
        else {
        try {
            inspec a=new inspec();
            a.Edit_violation(voi_id.getText(), vio_name.getText(), vio_add.getText(), vio_com.getText());
          JOptionPane.showMessageDialog(rootPane,"Done !!");
            voi_id.setText("");
            vio_name.setText("");
            vio_com.setText("");
            vio_add.setText("");
            vio_name.setEditable(false);
        vio_add.setEditable(false);
        vio_com.setEditable(false);
        editButton.setEnabled(false);
        } catch (IOException ex) {
            Logger.getLogger(Editvol.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Editvol.class.getName()).log(Level.SEVERE, null, ex);
        }
       // JOptionPane.showMessageDialog(rootPane, "Done");
        }
      ImageIcon prodimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ipage-admin-icon_1.png")));
        Image x = prodimg.getImage();
        Image y = x.getScaledInstance(pic.getWidth(),pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(y);
        pic.setIcon(image);
    }//GEN-LAST:event_editButtonActionPerformed

    private void voi_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voi_idMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_voi_idMouseClicked

    private void voi_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voi_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voi_idActionPerformed
String x;

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(voi_id.getText().equals("")) JOptionPane.showMessageDialog(rootPane, "Please Enter the Id","Error",JOptionPane.ERROR_MESSAGE);     
        x=voi_id.getText();
  vio_name.setEditable(true);
        vio_add.setEditable(true);
        vio_com.setEditable(true);
        editButton.setEnabled(true);
        try {
            inspec a=new inspec();
           a.LoadviolationCurrentList();
           boolean exist=false;
            for(Map.Entry k:a.Old_build.entrySet()){
               String key = k.getKey().toString();
              if(k.getKey().toString().equals(voi_id.getText())){
                    Vector v1=(Vector)k.getValue();
                    vio_name.setText((String) v1.get(0));
                    vio_add.setText((String) v1.get(1));
                    vio_com.setText((String) v1.get(2));
                    
                    // System.out.print(a.LoadImage(x));
                      exist=true;
              }  
        ImageIcon prodimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ipage-admin-icon_1.png")));
        Image x = prodimg.getImage();
        Image y = x.getScaledInstance(pic.getWidth(),pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(y);
        pic.setIcon(image);
            }          
              if(!exist){
                           exciption w=new exciption( "Invalid Id");
            JOptionPane.showMessageDialog(rootPane,w.view_exciption(),"Error",JOptionPane.ERROR_MESSAGE);
            voi_id.setText("");
              }
              if(voi_id.getText().equals("1")){
        ImageIcon prodimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("th (1).jpg")));
        Image x = prodimg.getImage();
        Image y = x.getScaledInstance(pic.getWidth(),pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(y);
        pic.setIcon(image);
       }
              else if(voi_id.getText().equals("2"))
              {
                  ImageIcon prodimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("th (2).jpg")));
        Image x = prodimg.getImage();
        Image y = x.getScaledInstance(pic.getWidth(),pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(y);
        pic.setIcon(image);
                  
              }
              else if(voi_id.getText().equals("3"))
              {
                  ImageIcon prodimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("th (3).jpg")));
        Image x = prodimg.getImage();
        Image y = x.getScaledInstance(pic.getWidth(),pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(y);
        pic.setIcon(image);
              }
              else if(voi_id.getText().equals("4"))
              {
                  ImageIcon prodimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("th (4).jpg")));
        Image x = prodimg.getImage();
        Image y = x.getScaledInstance(pic.getWidth(),pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(y);
        pic.setIcon(image);
              }
        } catch (IOException ex) {
            Logger.getLogger(Editvol.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Editvol.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editvol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField vio_add;
    private javax.swing.JTextArea vio_com;
    private javax.swing.JTextField vio_name;
    private javax.swing.JTextField voi_id;
    // End of variables declaration//GEN-END:variables
}
